---
- name: Configure DevOps Lab Server
  hosts: devops
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - docker.io
          - git
          - curl
        state: present

    - name: Enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started
