name: DevOps CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t devops-virtual-lab:${{ github.sha }} ./app

      - name: Validate Kubernetes manifests
        run: |
          grep -q "kind: Deployment" k8s/deployment.yml
          grep -q "kind: Service" k8s/service.yml
